version: "3.8"

services:
  remix:
    image: registry.gitlab.com/ludo237/ludo237.com/remix:production
    container_name: ludo_remix
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./database.db:/usr/src/app/prisma/database.db
    ports:
      - "3002:3000"
    networks:
      - ludo

networks:
  ludo:
    external: false
    name: ludo
